version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/ruby:2.5.7-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: ubuntu
          RAILS_ENV: test

      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: ladle_test

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: authenticate with Gemini
          command: |
            bundle config gemini.atl.appfolio.net $GEMINI_USER:$GEMINI_PASSWORD

      - run: # Install rugged/libgit2 dependencies
          name: CMake Install
          command: sudo apt-get install cmake

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: configure attr_accessor keys
          command: |
            echo 'export TOKEN_KEY=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`' >> $BASH_ENV

      - run: RAILS_ENV=test bundle exec rake db:create
      - run: RAILS_ENV=test bundle exec rake db:schema:load
      - run: RAILS_ENV=test bundle exec rake db:seed

      - run:
          name: run tests
          command: |
            bundle exec rake test

      - store_artifacts:
          path: ~/repo/log

  sourceclear:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name:  SourceClear Scan
          command: |
              git clone -b $SRCCLR_GIT_RELEASE git@github.com:appfolio/security-ids.git ~/security-ids --single-branch
              ~/security-ids/scripts/srcclr_circle-ci.sh -c 'ladle-guild'

workflows:
  version: 2.1
  rc:
    jobs:
      - build-and-test:
          context: appfolio_test_context

  scheduled:
    triggers:
      - schedule:
          cron: "0 14 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - sourceclear:
          context: appfolio_sourceclear
