version: 2.1
orbs:
  static-code-analysis: appfolio/static-code-analysis@volatile

jobs:
  build-and-test:
    docker:
      - image: &ruby_image circleci/ruby:2.6.3-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: ubuntu
          RAILS_ENV: test

      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: ladle_test

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: authenticate with Gemini
          command: |
            bundle config gemini.atl.appfolio.net $GEMINI_USER:$GEMINI_PASSWORD

      - run: # Install rugged/libgit2 dependencies
          name: CMake Install
          command: sudo apt-get update; sudo apt-get install cmake

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: configure attr_accessor keys
          command: |
            echo 'export TOKEN_KEY=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`' >> $BASH_ENV

      - run: RAILS_ENV=test bundle exec rake db:create
      - run: RAILS_ENV=test bundle exec rake db:schema:load
      - run: RAILS_ENV=test bundle exec rake db:seed

      - run:
          name: run tests
          command: |
            bundle exec rake test

      - store_artifacts:
          path: ~/repo/log

workflows:
  version: 2.1
  rc:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - build-and-test:
          context: appfolio_test_context
  nightly-static-code-security-analysis:
    # Configure trigger at https://app.circleci.com/settings/project/github/appfolio/ladle/triggers
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ "Nightly static code security analysis", << pipeline.schedule.name >> ]
    jobs:
      - static-code-analysis/scan:
          context: appfolio_static-code-analysis
      - static-code-analysis/report:
          context: appfolio_static-code-analysis
          requires:
            - static-code-analysis/scan
