# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58c6d8625d6186c521198b048414f055835d95237e89469a29b3c0087b4506867e0ad0a4b7f24dec80a5b51028bf5ea4cd2bb5fb85def8a1d5e197127b5c2efd
  token_key: <%= ENV["TOKEN_KEY"] %>

test:
  secret_key_base: 9b1c9af0441c6b2533b3b0fff3da1a48df4333c680a4c23d9b8d9d2b81add4b10ef7124ab9b0741a757bb9115dc683af7a433b9ae164d9af7c4c3c9c28a181dd
  token_key: <%= ENV["TOKEN_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  token_key: <%= ENV["TOKEN_KEY"] %>
